"""empty message

Revision ID: 4502d6b4665e
Revises: init
Create Date: 2020-06-22 18:10:50.479240

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4502d6b4665e'
down_revision = None
branch_labels = None
depends_on = None


# ----- types ----------------------
dep = postgresql.ENUM('ld', 'tr', 'yt', 'au', 'ps', 'ae', name='dep', create_type=False)
ann_level = postgresql.ENUM('tips', 'normal', 'important', name='ann_level', create_type=False)
proj_cat = postgresql.ENUM('doc', 'sub', 'ani', name='proj_cat', create_type=False)
proj_status = postgresql.ENUM('pre', 'freezed', 'working', 'upload', 'fin', name='proj_status', create_type=False)
pit_status = postgresql.ENUM('init', 'pending', 'working', 'delayed', 'past_due', 'auditing', 'fin', 'fin_p', 'dropped', name='pit_status', create_type=False)


def upgrade():
    dep.create(bind=op.get_bind())
    ann_level.create(bind=op.get_bind())
    proj_cat.create(bind=op.get_bind())
    proj_status.create(bind=op.get_bind())
    pit_status.create(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pink',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('qq', sa.String(), nullable=True),
    sa.Column('other', sa.String(), nullable=True),
    sa.Column('deps', postgresql.ARRAY(dep), nullable=False),
    sa.Column('_pwd', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_pink_name'), 'pink', ['name'], unique=True)
    op.create_table('ann',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('level', ann_level, nullable=False),
    sa.Column('deps', postgresql.ARRAY(dep), nullable=False),
    sa.Column('poster_id', sa.String(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('ver', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['pink.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ann_deps'), 'ann', ['deps'], unique=False)
    op.create_table('duck',
    sa.Column('pink_id', sa.String(), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('allow', sa.Boolean(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['pink_id'], ['pink.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pink_id', 'node'),
    sa.UniqueConstraint('pink_id', 'node', name='_duck_uc')
    )
    op.create_table('lemon',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('pink_id', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('device_id', postgresql.UUID(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pink_id'], ['pink.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pink_id', 'device_id', name='_lemon_uc')
    )
    op.create_table('proj',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('cat', proj_cat, nullable=False),
    sa.Column('suff', sa.String(), nullable=False),
    sa.Column('status', proj_status, nullable=False),
    sa.Column('leader_id', sa.String(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('finish_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('track', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['pink.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'cat', 'suff', name='_proj_uc')
    )
    op.create_index(op.f('ix_proj_title'), 'proj', ['title'], unique=False)
    op.create_table('chat',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('proj_id', sa.String(), nullable=False),
    sa.Column('pink_id', sa.String(), nullable=False),
    sa.Column('reply_to_id', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('ver', sa.Integer(), nullable=False),
    sa.Column('reply_to_ver', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['pink_id'], ['pink.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proj_id'], ['proj.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('proj_id', sa.String(), nullable=False),
    sa.Column('dep', dep, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proj_id'], ['proj.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('proj_id', 'dep', 'name', name='_role_uc')
    )
    op.create_index(op.f('ix_role_dep'), 'role', ['dep'], unique=False)
    op.create_table('pit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('pink_id', sa.String(), nullable=False),
    sa.Column('status', pit_status, nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('finish_at', sa.DateTime(), nullable=True),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('track', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['pink_id'], ['pink.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pit_status'), 'pit', ['status'], unique=False)
    op.create_table('mango',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pit_id', sa.String(), nullable=False),
    sa.Column('ver', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('sha1', sa.String(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metainfo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['pit_id'], ['pit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pit_id', 'ver', name='_mango_uc'),
    sa.UniqueConstraint('sha1')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mango')
    op.drop_index(op.f('ix_pit_status'), table_name='pit')
    op.drop_table('pit')
    op.drop_index(op.f('ix_role_dep'), table_name='role')
    op.drop_table('role')
    op.drop_table('chat')
    op.drop_index(op.f('ix_proj_title'), table_name='proj')
    op.drop_table('proj')
    op.drop_table('lemon')
    op.drop_table('duck')
    op.drop_index(op.f('ix_ann_deps'), table_name='ann')
    op.drop_table('ann')
    op.drop_index(op.f('ix_pink_name'), table_name='pink')
    op.drop_table('pink')
    # ### end Alembic commands ###
    dep.drop(bind=op.get_bind())
    ann_level.drop(bind=op.get_bind())
    proj_cat.drop(bind=op.get_bind())
    proj_status.drop(bind=op.get_bind())
    pit_status.drop(bind=op.get_bind())
